name: Download .NET initial SDK and Artifacts

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted

    permissions:
      contents: write

    steps:

    - name: Create assets dir
      run: |
        mkdir assets
        ls -lR assets

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dotnet-linux-loongarch64-artifacts
        github-token: ${{ secrets.CLONE_TOKEN }}
        repository: chenguohui/dotnet-loongarch
        run-id: 15897980901
        path: assets/

    - name: Display structure of downloaded files
      run: ls -lR assets/
