name: Upload .NET initial SDK and Artifacts

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted

    permissions:
      contents: write

    steps:

    - name: List assets directory
      run: find ~/assets

    - name: Upload .NET
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-linux-loongarch64-artifacts
        path: |
          ~/assets/dotnet-sdk-*.tar.gz
          ~/assets/Private.SourceBuilt.Artifacts.*.tar.gz
        compression-level: 0  # all artifacts are already compressed

